POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username":"aaaaa",
    "password":"aaaaa"
}

###

POST http://localhost:3000/api/auth/logout
Content-Type: application/json



###