POST http://localhost:3000/api/messages
Content-Type: application/json

{
    "clubId":1,
    "title":"oooooooo",
    "message":"ooooooooaaa"

}
###
GET http://localhost:3000/api/messages
Content-Type: application/json

