POST http://localhost:3000/api/messages
Content-Type: application/json

{
    "clubId":1,
    "title":"oooooooo",
    "message":"ooooooooaaa"

}
###
GET http://localhost:3000/api/messages
Content-Type: application/json

###

GET http://localhost:3000/api/messages/8
Content-Type: application/json

###

PUT http://localhost:3000/api/messages/9
Content-Type: application/json

{
    "title":"xxxxxx",
    "text":"xxxxxxxxxxxxxx"
}

###
DELETE  http://localhost:3000/api/messages/14
Content-Type: application/json

